on: 
push:
  branches: - master
name:  Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with: 
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp://51.79.185.161
        ftp-username: demoProject
        ftp-password: ${{ secrets.ftp_password }}